<BoxLayoutWidget>:
    Button:
        text:'Btn0'
        backgroud_color:[0,1,1,1]
        font_size: 20
    Button:
        text:'Btn1'
        backgroud_color: [0,1,0,1]
        font_size: 20
    Button:
        text:'Btn2'
        backgroud_color: [0,0,1,1]
        font_size: 20
    Button:
        text:'Btn3'
        backgroud_color: [1,0,1,1]
        font_size: 20
    Button:
        text:'Btn4'
        backgroud_color: [1,0,0,1]
        font_size: 20